/* ============================================================
   作品與經歷資料 ── 全站只維護這一份
   首頁 (index.html) 和作品詳情頁 (work.html) 都讀這裡。

   要新增一件作品：複製一個 { ... } 區塊，改內容即可。
   id        網址用的代號（英文、不重複），詳情頁網址會是 work.html?id=這個值
   category  'dashboard'（儀表板）/ 'tool'（工具）/ 'edu'（互動教學）
   seed      暫時的示意圖關鍵字；換成真實作品時把圖片網址改成你的截圖路徑
   ============================================================ */

window.works = [
  {
    id: 'yebuda-shop',
    title: 'Yebuda 首爾精選電商',
    category: 'web',
    tag: '全棧電商',
    blurb: '正韓選品電商全棧：顧客前台、老闆後台 CMS、綠界金流與營收儀表板，從前到後一條龍自己做。',
    metric: '前台→金流一條龍',
    images: ['images/yebuda-shop.jpg'],
    live: 'https://yebuda-shop.fly.dev/',
    repo: 'https://github.com/purecolor522/Yebuda2026',
    // 旗艦案例：保留詳情頁（不設 direct），讓人讀完整 case study 再連到線上版／原始碼
    summary: '從前台、後台、金流到部署，一個人做完的正韓選品電商。顧客能逛、能買、能結帳；老闆有密碼保護後台，自己管 37 件商品、訂單與營收儀表板。',
    role: '產品 + 全棧開發',
    timeline: '已上線（Fly.io / Render）',
    team: '獨立完成',
    tools: ['Node.js / Express', '綠界 ECPay', 'JWT / bcrypt', 'Docker', 'Fly.io'],
    problem: '正韓選品多靠 IG 私訊接單，賣家被報價、湊團、對帳綁住；想轉成正式網站，又卡在「要找工程師、金流難串」。目標：一套顧客信任、老闆能自己長期營運的店。',
    insight: '兩種人、兩種痛：顧客被官網等級的體驗養刁，土砲表單會直接關掉；賣家想專業化卻被技術擋住。關鍵是——決定產品活不活得下去的不是前台多炫，而是「老闆離開工程師後，能不能自己營運」。',
    personas: [
      { who: '顧客', need: '像逛品牌官網一樣好逛、結帳安心，才願意下單。' },
      { who: '店主 / 老闆', need: '不靠工程師就能上架、改價、看營收，自己長期經營。' },
    ],
    approach: [
      { step: '前台購物體驗', text: '輪播、分類、商品詳情（顏色／尺寸／數量）、購物車到結帳，全程 RWD。' },
      { step: '老闆後台 CMS', text: '密碼保護後台，多圖上架、改庫存標籤、管訂單與物流——讓老闆脫離工程師。' },
      { step: '金流串接', text: '整合綠界 ECPay，支援信用卡／Apple Pay／ATM／超商，處理通知與付款導回。' },
      { step: '營收儀表板', text: '總營收、本月營收、客單價、30 日曲線與熱銷單品，讓老闆用數字決策。' },
      { step: '一鍵部署', text: 'Docker + GitHub Actions 自動部署到 Fly.io，推一次就上線。' },
    ],
    decisions: [
      { choice: '「老闆自助營運」擺第一', why: '賣家最痛的是依賴工程師，所以後台 CMS 與營收儀表板優先於行銷版位——這才是產品的命脈。' },
      { choice: '金流用綠界、先跑測試環境', why: '賣家與顧客都信任綠界。先用 stage 把整條付款流程打通、降低上線風險，再切正式金鑰。' },
      { choice: '這版不做會員與優惠券', why: '先驗證「逛→買→收款」核心；行銷放大器留到核心成立後再加。' },
      { choice: '購物車免註冊', why: '結帳多一道手續就多一段流失，先讓人買得到。' },
    ],
    reflection: [
      '最有感的不是前台多漂亮，而是老闆發現「我自己就能改價、看營收」——印證了把自助營運放第一。',
      '砍掉會員讓核心更快跑通；下一步要驗證回購，會員與再行銷才會變優先。',
      '重做的話會更早接真實賣家的商品與訂單，讓成果有真實營收數字。',
    ],
    outcomes: [
      { value: '老闆自助', label: '上架、改庫存、看訂單與營收全在後台，營運不必再找工程師' },
      { value: '4 種金流', label: '信用卡 / Apple Pay / ATM / 超商，完整串接綠界 ECPay' },
      { value: '一鍵上線', label: 'Docker + GitHub Actions 自動部署，推一次即上線' },
    ],
  },
  {
    id: 'budget-dashboard',
    title: '經費控管儀表板',
    category: 'dashboard',
    tag: '儀表板',
    blurb: '把年度預算、月度執行與主計帳對帳整合到同一個畫面，讓承辦與主管即時看到餘額與超支風險。',
    metric: '對帳工時 ↓ ~75%',
    seed: 'budget-dashboard-finance-grid',
    images: ['images/budget-dashboard.jpg'],
    // ── 以下為詳情頁欄位 ──
    summary: '為政府機關設計的單頁經費控管儀表板，整合預算分配、執行進度與主計帳對帳（示範版資料已去識別化）。',
    role: '產品 + 自建',
    timeline: '單檔網頁應用',
    team: '獨立完成',
    tools: ['HTML / CSS / JS', 'SheetJS (Excel)', 'localStorage'],
    live: 'https://purecolor522.github.io/budget-dashboard/',
    direct: true,  // 首頁卡片直接開啟儀表板，跳過詳情頁
    problem: '政府機關的經費執行常常分配計畫與實際支出脫節，跨系統對帳要人工逐筆比對，承辦與主管很難即時掌握每個科目的餘額與超支風險。',
    approach: [
      { step: '盤點流程', text: '從預算分配、執行登錄到主計對帳，把承辦每個月實際要做的事拆解清楚，找出最花時間的對帳環節。' },
      { step: '單一畫面整合', text: '把年度預算、分期分配、月度執行與主計帳放到同一個儀表板，並依財源別、資本門與經常門分層呈現。' },
      { step: '自動對帳與預警', text: '系統依金額自動配對主計分類帳、支援逐筆手動勾稽，並對接近上限或超支的科目即時視覺預警。' },
      { step: '本機可編輯', text: '用 Excel 一鍵匯入更新、瀏覽器自動存檔、支援 JSON / CSV 備份，不必架伺服器也能用。' },
    ],
    outcomes: [
      { value: '~75% ↓', label: '每月對帳工時：逐筆人工比對 → 系統自動配對' },
      { value: '19 科目', label: '一個畫面即時掌握餘額與超支風險' },
      { value: '零後端', label: 'Excel 一鍵匯入、瀏覽器自動存檔，免架站即可用' },
    ],
    gallery: ['budget-dashboard-kpi', 'budget-dashboard-reconcile', 'budget-dashboard-detail'],
  },
  {
    id: 'marc21-cataloger',
    title: 'MARC21 編目工具',
    category: 'tool',
    tag: '工具 · 自動化',
    blurb: '依國家圖書館規則自動著錄與檢核中文圖書書目，讓編目員少犯規則錯誤、加快流程。',
    metric: '20+ 規則即時檢核',
    seed: 'marc21-cataloging-library',
    images: ['images/marc21.jpg'],
    summary: '為圖書館編目員設計的網頁工具，自動化 MARC21 書目的著錄、檢核與匯出，已部署上線。',
    role: '產品 + 自建',
    timeline: '已上線',
    team: '獨立完成',
    tools: ['HTML / CSS / JS', 'Google Books API', 'OpenLibrary API', 'GitHub Pages'],
    live: 'https://purecolor522.github.io/marc21-cataloger/',
    direct: true,  // 首頁卡片直接開啟工具
    problem: '國家圖書館的中文圖書著錄規則超過 1600 頁，編目員手工著錄時很容易漏掉定長欄位或分欄符等細節，導致紀錄不合規、要反覆修正。',
    approach: [
      { step: '拆解規則', text: '把國圖《中文圖書編目 MARC21 著錄注意事項》整理成可程式化的檢核規則，排出最常出錯、最值得自動化的項目。' },
      { step: '著錄台', text: '做出表單式著錄介面，輸入 ISBN 自動帶入書目，支援 MARCXML、.mrc、NBInet 等多種格式貼上與匯入。' },
      { step: '檢核工具', text: '逐欄即時比對 20 多項規則，提供含文件依據的自動修正建議，並列出需要人工判斷的清單。' },
      { step: '部署上線', text: '純前端、無伺服器執行，保護資料隱私，直接部署到 GitHub Pages 給編目員使用。' },
    ],
    outcomes: [
      { value: '1600 頁', label: '把國圖著錄規則濃縮成 20+ 條即時自動檢核' },
      { value: '逐欄即時', label: '輸入當下就抓錯並附文件依據的修正建議，減少反覆退件' },
      { value: '4 種格式', label: 'MARCXML / .mrc / NBInet 一鍵匯入匯出' },
    ],
    gallery: ['marc21-bench', 'marc21-checker', 'marc21-import'],
  },
  {
    id: 'scale-stairs',
    title: '音階小教室',
    category: 'edu',
    tag: '互動教學',
    blurb: '用互動鋼琴、圖解和爬樓梯小遊戲，把大調音階的「全全半」公式變得看得到、也玩得到。',
    metric: '7×4 音階 · 免安裝',
    seed: 'music-scale-stairs-game',
    images: ['images/scale-stairs.jpg'],
    live: 'https://purecolor522.github.io/scale-stairs/',
    direct: true,  // 首頁卡片直接開啟教具
    summary: '一個把抽象樂理視覺化、遊戲化的互動網頁教具，幫音樂初學者用聽、看、玩記住音階結構。',
    role: '產品 + 自建',
    timeline: '已上線',
    team: '獨立完成',
    tools: ['HTML / CSS / JS', 'Web Audio API', 'SVG 動畫'],
    problem: '傳統樂理教學太抽象，初學者得硬背「全全半全全全半」的大調音階公式，很難把琴鍵、聲音和規則連在一起。',
    approach: [
      { step: '互動鋼琴', text: '可點、也可用電腦鍵盤彈的虛擬鋼琴，每個音即時發聲，先讓使用者用耳朵建立感覺。' },
      { step: '圖解音階', text: '用動畫箭線標出全音與半音的級進，把抽象的音階結構直接畫成看得懂的圖。' },
      { step: '階梯遊戲', text: '小音符爬樓梯，玩家選「全音」或「半音」蓋出完整大調，答對即時加分、連對加成。' },
      { step: '提示與難度', text: '可開關提示模式降低門檻，支援多個主音與音階類型，讓不同程度都能練習。' },
    ],
    outcomes: [
      { value: '聽 + 看 + 玩', label: '把抽象的「全全半」公式變成可操作的互動體驗' },
      { value: '7 × 4', label: '7 個主音 × 4 種音階，涵蓋初學常用範圍' },
      { value: '0 安裝', label: '純網頁、開瀏覽器就能玩，老師可直接帶課堂使用' },
    ],
    gallery: ['music-scale-keyboard', 'music-scale-diagram', 'music-scale-stairs'],
  },
  {
    id: 'twstock-eval',
    title: '台股評估儀表板',
    category: 'dashboard',
    tag: '儀表板 · 量化分析',
    blurb: '以短／中／長三維度自動為台股個股與 ETF 評分，每項指標都附原始數值、白話解讀與評估準則，建立可重複、有依據的選股流程。',
    metric: '1800 檔 < 3 秒掃描',
    seed: 'twstock-quant-dashboard-candles',
    images: ['images/twstock-eval.svg'],
    live: 'https://twstock-eval.fly.dev/',
    direct: true,  // 首頁卡片直接開啟儀表板
    summary: '一個把公開技術面與基本面指標量化成評分的台股研究工具：自動掃描全市場、偵測進場訊號、回測勝率，並用兩個紙上交易帳戶讓「我的判斷」對決「AI 操盤」。（僅供研究參考，不構成投資建議。）',
    role: '產品 + 全棧開發',
    timeline: '持續開發中',
    team: '獨立完成',
    repo: 'https://github.com/purecolor522/twstock-eval',
    tools: ['HTML / CSS / JS', '後端 API（行情 / 籌碼）', 'localStorage + 後端持久化', 'launchd 排程'],
    problem: '散戶看盤時資訊散落各處，技術面、基本面、籌碼與新聞要在多個網站之間切換，而且「這檔到底好不好」常憑感覺，缺少一套可重複、有準則、能回測驗證的判斷流程。',
    approach: [
      { step: '三維度量化評分', text: '把指標拆成短／中／長期三個維度評分，每項都列出原始數值、白話解讀與評估準則，分數怎麼來一清二楚。' },
      { step: '自動獵手與選股器', text: '全市場掃約 1800 檔，偵測突破、均線多頭、爆量與動能等進場條件，並用 ATR 算出進場／停損／目標／風報比。' },
      { step: '回測驗證', text: '訊號自動入庫，依後續股價回推勝率與期望值；評分以 point-in-time 重算，驗證「評分↔未來報酬」是否真的有效。' },
      { step: 'AI 操盤對決', text: '兩個各 1000 萬的紙上帳戶——手動下單 vs 決策引擎自動挑買賣點，模擬手續費與證交稅即時結算損益，比誰賺得多。' },
    ],
    outcomes: [
      { value: '1800 檔 / <3 秒', label: '全市場選股，取代逐檔人工看盤' },
      { value: '3 維 + 回測', label: '短中長期評分，並以歷史勝率驗證評分是否真的有效' },
      { value: 'AI vs 我', label: '兩個紙上帳戶對決，量化驗證自己的判斷準確度' },
    ],
    gallery: ['twstock-score', 'twstock-hunter', 'twstock-battle'],
  },

  /* ── 專案統籌 / 活動企劃（PM 案例，category: 'event'）── */
  {
    id: 'light-festival',
    title: '光の慶典 草地敬拜音樂節',
    category: 'event',
    tag: '活動統籌 · PM',
    blurb: '4 小時戶外音樂節、13 組表演、近 50 位表演者：我負責節目統籌，把名單、試音、現場換場與音響排成一條準時、不冷場的流程。',
    metric: '13 組 · ~48 位表演者',
    images: ['images/light-festival.svg'],
    summary: '一場給福音朋友與夥伴教會的戶外草地音樂節：音樂演出 × 市集 × 生命故事。我擔任節目統籌，把 13 組表演、近 50 位表演者、完整舞台音響與多間教會的協作，排成一條準時、不冷場的流程。',
    role: '節目統籌 / 活動製作（PM）',
    timeline: '2024 · 約 6 週籌備',
    team: '跨組志工團隊（場佈／音控／市集／主持／夥伴教會）',
    tools: ['流程／試音排程', '舞台音響規劃', '跨組協作'],
    problem: '一場 4 小時、13 組表演、近 50 位表演者的戶外音樂節，要在當天有限的彩排時間內讓每組都試到音、現場無縫換場不冷場，同時市集與表演並行、還要對接多間夥伴教會。難的不是單一表演，而是「在大量變數和志工團隊下，把整場準時、順暢地跑完」。',
    insight: '這種活動的成敗不在哪一組表演多精彩，而在「銜接」——換場、試音、節奏。觀眾體驗是連續的，一個冷場或技術出包就破壞氣氛；所以排程與分工的設計，比內容本身更關鍵。',
    personas: [
      { who: '福音朋友（第一次來的人）', need: '氣氛輕鬆、有得看也有得逛、沒有壓力，才願意留下來。' },
      { who: '表演者 / 同工', need: '清楚的試音與上下台流程，知道自己幾點該在哪、用什麼器材。' },
    ],
    approach: [
      { step: '確認與排序節目', text: '收齊 13 組的需求，排出演出順序與時長，定出整晚的節目流程。' },
      { step: '設計試音時間表', text: '把 13 組壓進當天下午、每組 15 分鐘連續試音，先解決「誰用什麼器材」的不確定。' },
      { step: '音響與舞台規格', text: '列出主喇叭、6 路監聽、6 支無線麥、鼓／鍵盤／貝斯收音等清單，確保器材到位。' },
      { step: '換場不冷場', text: '每次技術換場都用市集介紹與主持填補，把空檔藏在節目裡，順便刺激市集消費。' },
      { step: '分工與當天執行', text: '場佈、音控、市集、主持、夥伴教會各組負責人明確，當天按表操課；我也親自擔任一段 DJ。' },
    ],
    decisions: [
      { choice: '把「換場不冷場」放第一', why: '觀眾體驗最怕空檔，所以用市集與主持把技術換場藏起來，比讓每組表演更炫更重要。' },
      { choice: '彩排集中在白天一次跑完', why: '用連續 15 分鐘的 slot 壓縮試音，確保晚上正式演出不開天窗。' },
      { choice: '表演與市集並行', why: '讓第一次來的福音朋友有得看也有得逛，降低「純聚會」的壓力——呼應活動主旨：建立關係。' },
    ],
    reflection: [
      '最有效的是「把技術換場藏進市集與主持」——觀眾幾乎感受不到空檔，整場節奏很順。',
      '下次會更早鎖定每組的器材需求，減少當天試音的來回。',
      '若要更有說服力，下次會在現場收集到場人數與回饋，讓成果有真實數據。',
    ],
    outcomes: [
      { value: '13 組 / ~48 人', label: '4 小時節目準時跑完，現場換場不冷場' },
      { value: '3 小時試音', label: '13 組各 15 分鐘連續完成，晚上正式零開天窗' },
      { value: '3 間教會', label: '跨教會協作（TBC / TNGNC / TKCH）共同促成' },
    ],
  },

  /* ── 平面設計作品（用真實圖片；images 放圖檔路徑，可放多張）── */
  {
    id: 'design-star-born',
    title: '一個巨星的誕生',
    category: 'design',
    tag: '平面設計 · 主視覺',
    blurb: '教會聖誕歡慶的主視覺海報，用燙金字與馬槽剪影營造溫暖而莊重的節慶氛圍。',
    metric: '聖誕活動主視覺',
    images: ['images/star-born.jpg'],
    summary: '為台南浸信會聖誕歡慶設計的主視覺海報，以「一個巨星的誕生」為題，金色光暈搭配耶穌降生馬槽剪影，呈現溫暖而莊重的節期氛圍。',
    role: '視覺設計',
    timeline: '聖誕節慶活動',
    team: '獨立完成',
    tools: ['Illustrator', 'Photoshop'],
  },
  {
    id: 'design-flea-market',
    title: '二手市集 系列主視覺',
    category: 'design',
    tag: '平面設計 · 系列',
    blurb: '同一個二手市集的兩季主視覺，從復古雕版到星空夜版，維持品牌識別又各有氛圍。',
    metric: '兩季系列海報',
    images: ['images/market.jpg', 'images/market-night.jpg'],
    summary: '為教會「Second Hand 二手市集」設計的系列主視覺。第一季以復古雕版插畫與牛皮紙質感呈現「好物」氛圍；第二季延伸為「星光市集」的星空夜版，維持一致的版式與標誌，氣氛卻完全不同。',
    role: '視覺設計',
    timeline: '兩季活動',
    team: '獨立完成',
    tools: ['Illustrator', 'Photoshop'],
  },
  {
    id: 'design-tbc-christmas',
    title: '玩轉聖誕節 TBC Story',
    category: 'design',
    tag: '平面設計 · 活動海報',
    blurb: '青年聖誕派對海報，用扭蛋、聖誕老人腰帶與明亮普普風，刻意和典雅款拉開反差。',
    metric: '青年活動海報',
    images: ['images/christmas.jpg'],
    summary: '為教會青年聖誕派對「TBC Story」設計的活動海報，以扭蛋、交換禮物為主題，採用明亮普普風與大膽字體，刻意和典雅的聖誕主視覺形成風格反差。',
    role: '視覺設計',
    timeline: '青年聖誕活動',
    team: '獨立完成',
    tools: ['Illustrator', 'Photoshop'],
  },
  {
    id: 'design-ordination',
    title: '按牧感恩禮拜 邀請卡',
    category: 'design',
    tag: '平面設計 · 邀請卡',
    blurb: '按牧典禮的正式邀請卡，以深藍配燙金的紋章與字體，呈現莊重而典雅的儀式感。',
    metric: '正式邀請卡',
    images: ['images/ordination.jpg'],
    summary: '為教會按牧感恩禮拜設計的正式邀請卡，採深藍與燙金的紋章式視覺與襯線字體，正反面一致，傳達莊重、典雅的儀式感。',
    role: '視覺設計',
    timeline: '按牧典禮',
    team: '獨立完成',
    tools: ['Illustrator', 'Photoshop'],
  },
  {
    id: 'design-mama-fun',
    title: '媽媽樂 親子園遊會',
    category: 'design',
    tag: '平面設計 · 活動海報',
    blurb: '母親節親子園遊會海報，用等角遊樂園插畫把闖關、手作與美食變成一座小樂園。',
    metric: '親子活動海報',
    images: ['images/mama.jpg'],
    summary: '為教會母親節「媽媽樂」親子園遊會設計的活動海報，以等角視覺打造「TBC happyland」遊樂園場景，串起親子手作、闖關活動與美食園遊會，活潑又好親近。',
    role: '視覺設計',
    timeline: '母親節活動',
    team: '獨立完成',
    tools: ['Illustrator', 'Photoshop'],
  },
];

window.experience = [
  { period: '年份待補', role: '負責人', company: '以勒樂集', desc: '統籌品牌行銷與社群經營，從內容企劃到成效追蹤；同時負責團隊招募、排班與人員管理，讓品牌聲量與內部運作一起成長。' },
  { period: '年份待補', role: '創辦人', company: '傳遞加創意工作室', desc: '創立文創品牌，一手包辦產品設計、品牌視覺與行銷推廣，並控管接案到交付的整體時程，把創意落地成可出貨的商品。' },
  { period: '年份待補', role: '負責人', company: 'Yebuda 漂亮小姐', desc: '經營正韓選品文創品牌，負責選品、品牌視覺與行銷操作，並管理上架到出貨的時程；延伸出自建電商 Yebuda（見作品）。' },
  { period: '年份待補', role: '負責人', company: 'SYH 音樂工作室', desc: '創辦音樂工作室，負責教學與課程設計，並開發自有教材；延伸出互動樂理教具「音階小教室」（見作品）。' },
];
