/* ============================================================
   作品與經歷資料 ── 全站只維護這一份
   首頁 (index.html) 和作品詳情頁 (work.html) 都讀這裡。

   要新增一件作品：複製一個 { ... } 區塊，改內容即可。
   id        網址用的代號（英文、不重複），詳情頁網址會是 work.html?id=這個值
   category  'dashboard'（儀表板）/ 'tool'（工具）/ 'edu'（互動教學）
   seed      暫時的示意圖關鍵字；換成真實作品時把圖片網址改成你的截圖路徑
   ============================================================ */

window.works = [
  {
    id: 'budget-dashboard',
    title: '經費控管儀表板',
    category: 'dashboard',
    tag: '儀表板',
    blurb: '把年度預算、月度執行與主計帳對帳整合到同一個畫面，讓承辦與主管即時看到餘額與超支風險。',
    metric: '三層自動對帳',
    seed: 'budget-dashboard-finance-grid',
    images: ['images/budget-dashboard.jpg'],
    // ── 以下為詳情頁欄位 ──
    summary: '為政府機關設計的單頁經費控管儀表板，整合預算分配、執行進度與主計帳對帳（示範版資料已去識別化）。',
    role: '產品 + 自建',
    timeline: '單檔網頁應用',
    team: '獨立完成',
    tools: ['HTML / CSS / JS', 'SheetJS (Excel)', 'localStorage'],
    live: 'https://purecolor522.github.io/budget-dashboard/',
    problem: '政府機關的經費執行常常分配計畫與實際支出脫節，跨系統對帳要人工逐筆比對，承辦與主管很難即時掌握每個科目的餘額與超支風險。',
    approach: [
      { step: '盤點流程', text: '從預算分配、執行登錄到主計對帳，把承辦每個月實際要做的事拆解清楚，找出最花時間的對帳環節。' },
      { step: '單一畫面整合', text: '把年度預算、分期分配、月度執行與主計帳放到同一個儀表板，並依財源別、資本門與經常門分層呈現。' },
      { step: '自動對帳與預警', text: '系統依金額自動配對主計分類帳、支援逐筆手動勾稽，並對接近上限或超支的科目即時視覺預警。' },
      { step: '本機可編輯', text: '用 Excel 一鍵匯入更新、瀏覽器自動存檔、支援 JSON / CSV 備份，不必架伺服器也能用。' },
    ],
    outcomes: [
      { value: '三層', label: '預算 · 分配 · 主計帳對帳' },
      { value: '19 科目', label: '涵蓋業務費與資本門' },
      { value: 'Excel', label: '一鍵匯入更新資料' },
    ],
    gallery: ['budget-dashboard-kpi', 'budget-dashboard-reconcile', 'budget-dashboard-detail'],
  },
  {
    id: 'marc21-cataloger',
    title: 'MARC21 編目工具',
    category: 'tool',
    tag: '工具 · 自動化',
    blurb: '依國家圖書館規則自動著錄與檢核中文圖書書目，讓編目員少犯規則錯誤、加快流程。',
    metric: '已上線 GitHub Pages',
    seed: 'marc21-cataloging-library',
    images: ['images/marc21.jpg'],
    summary: '為圖書館編目員設計的網頁工具，自動化 MARC21 書目的著錄、檢核與匯出，已部署上線。',
    role: '產品 + 自建',
    timeline: '已上線',
    team: '獨立完成',
    tools: ['HTML / CSS / JS', 'Google Books API', 'OpenLibrary API', 'GitHub Pages'],
    live: 'https://purecolor522.github.io/marc21-cataloger/',
    problem: '國家圖書館的中文圖書著錄規則超過 1600 頁，編目員手工著錄時很容易漏掉定長欄位或分欄符等細節，導致紀錄不合規、要反覆修正。',
    approach: [
      { step: '拆解規則', text: '把國圖《中文圖書編目 MARC21 著錄注意事項》整理成可程式化的檢核規則，排出最常出錯、最值得自動化的項目。' },
      { step: '著錄台', text: '做出表單式著錄介面，輸入 ISBN 自動帶入書目，支援 MARCXML、.mrc、NBInet 等多種格式貼上與匯入。' },
      { step: '檢核工具', text: '逐欄即時比對 20 多項規則，提供含文件依據的自動修正建議，並列出需要人工判斷的清單。' },
      { step: '部署上線', text: '純前端、無伺服器執行，保護資料隱私，直接部署到 GitHub Pages 給編目員使用。' },
    ],
    outcomes: [
      { value: '20+', label: '自動檢核規則' },
      { value: '4 種', label: 'MARC 格式匯入匯出' },
      { value: '已上線', label: '部署於 GitHub Pages' },
    ],
    gallery: ['marc21-bench', 'marc21-checker', 'marc21-import'],
  },
  {
    id: 'scale-stairs',
    title: '音階小教室',
    category: 'edu',
    tag: '互動教學',
    blurb: '用互動鋼琴、圖解和爬樓梯小遊戲，把大調音階的「全全半」公式變得看得到、也玩得到。',
    metric: '已上線 · 可線上玩',
    seed: 'music-scale-stairs-game',
    images: ['images/scale-stairs.jpg'],
    live: 'https://purecolor522.github.io/scale-stairs/',
    summary: '一個把抽象樂理視覺化、遊戲化的互動網頁教具，幫音樂初學者用聽、看、玩記住音階結構。',
    role: '產品 + 自建',
    timeline: '已上線',
    team: '獨立完成',
    tools: ['HTML / CSS / JS', 'Web Audio API', 'SVG 動畫'],
    problem: '傳統樂理教學太抽象，初學者得硬背「全全半全全全半」的大調音階公式，很難把琴鍵、聲音和規則連在一起。',
    approach: [
      { step: '互動鋼琴', text: '可點、也可用電腦鍵盤彈的虛擬鋼琴，每個音即時發聲，先讓使用者用耳朵建立感覺。' },
      { step: '圖解音階', text: '用動畫箭線標出全音與半音的級進，把抽象的音階結構直接畫成看得懂的圖。' },
      { step: '階梯遊戲', text: '小音符爬樓梯，玩家選「全音」或「半音」蓋出完整大調，答對即時加分、連對加成。' },
      { step: '提示與難度', text: '可開關提示模式降低門檻，支援多個主音與音階類型，讓不同程度都能練習。' },
    ],
    outcomes: [
      { value: '可線上玩', label: '部署於 GitHub Pages' },
      { value: '7 × 4', label: '主音 × 音階類型' },
      { value: '視 + 聽 + 玩', label: '三管齊下學音階' },
    ],
    gallery: ['music-scale-keyboard', 'music-scale-diagram', 'music-scale-stairs'],
  },
  {
    id: 'yebuda-shop',
    title: 'Yebuda 首爾精選電商',
    category: 'web',
    tag: '全棧電商',
    blurb: '正韓選品電商全棧：顧客前台、老闆後台 CMS、綠界金流與營收儀表板，從前到後一條龍自己做。',
    metric: '已上線 · 全棧電商',
    images: ['images/yebuda-shop.jpg'],
    live: 'https://yebuda-shop.fly.dev/',
    summary: '一套自己從前台到後台、金流到部署做完的正韓選品電商。顧客端可瀏覽、加購與結帳；老闆端有密碼保護的後台，管理商品、訂單與營收儀表板。',
    role: '產品 + 全棧開發',
    timeline: '已上線（Fly.io / Render）',
    team: '獨立完成',
    tools: ['Node.js / Express', '綠界 ECPay', 'JWT / bcrypt', 'Docker', 'Fly.io'],
    problem: '想幫正韓選品賣家做一個能自己營運的網路商店：顧客要好逛好買，老闆要能自己上架商品、看訂單與營收，不必每次都找工程師。',
    approach: [
      { step: '前台購物體驗', text: '首頁主視覺輪播、分類與商品列表、商品詳情（顏色／尺寸／數量）、購物車與結帳，全程 RWD。' },
      { step: '老闆後台 CMS', text: '密碼保護的 /admin 後台，可多圖上架、調整庫存與標籤、管理訂單狀態與物流單號。' },
      { step: '金流串接', text: '整合綠界 ECPay，支援信用卡、Apple Pay、ATM 與超商，並處理 server 通知與付款導回。' },
      { step: '營收儀表板', text: '後台儀表板呈現總營收、本月營收、訂單數、客單價、30 日營收曲線與熱銷單品。' },
      { step: '一鍵部署', text: '用 Docker 打包，透過 GitHub Actions 自動部署到 Fly.io，另備 Render 藍圖，推一次就上線。' },
    ],
    outcomes: [
      { value: '前台＋後台', label: '顧客端與老闆 CMS 全包' },
      { value: 'ECPay', label: '綠界金流完整串接' },
      { value: '已上線', label: 'Docker + Fly.io 自動部署' },
    ],
  },

  /* ── 平面設計作品（用真實圖片；images 放圖檔路徑，可放多張）── */
  {
    id: 'design-star-born',
    title: '一個巨星的誕生',
    category: 'design',
    tag: '平面設計 · 主視覺',
    blurb: '教會聖誕歡慶的主視覺海報，用燙金字與馬槽剪影營造溫暖而莊重的節慶氛圍。',
    metric: '聖誕活動主視覺',
    images: ['images/star-born.jpg'],
    summary: '為台南浸信會聖誕歡慶設計的主視覺海報，以「一個巨星的誕生」為題，金色光暈搭配耶穌降生馬槽剪影，呈現溫暖而莊重的節期氛圍。',
    role: '視覺設計',
    timeline: '聖誕節慶活動',
    team: '獨立完成',
    tools: ['Illustrator', 'Photoshop'],
  },
  {
    id: 'design-flea-market',
    title: '二手市集 系列主視覺',
    category: 'design',
    tag: '平面設計 · 系列',
    blurb: '同一個二手市集的兩季主視覺，從復古雕版到星空夜版，維持品牌識別又各有氛圍。',
    metric: '兩季系列海報',
    images: ['images/market.jpg', 'images/market-night.jpg'],
    summary: '為教會「Second Hand 二手市集」設計的系列主視覺。第一季以復古雕版插畫與牛皮紙質感呈現「好物」氛圍；第二季延伸為「星光市集」的星空夜版，維持一致的版式與標誌，氣氛卻完全不同。',
    role: '視覺設計',
    timeline: '兩季活動',
    team: '獨立完成',
    tools: ['Illustrator', 'Photoshop'],
  },
  {
    id: 'design-tbc-christmas',
    title: '玩轉聖誕節 TBC Story',
    category: 'design',
    tag: '平面設計 · 活動海報',
    blurb: '青年聖誕派對海報，用扭蛋、聖誕老人腰帶與明亮普普風，刻意和典雅款拉開反差。',
    metric: '青年活動海報',
    images: ['images/christmas.jpg'],
    summary: '為教會青年聖誕派對「TBC Story」設計的活動海報，以扭蛋、交換禮物為主題，採用明亮普普風與大膽字體，刻意和典雅的聖誕主視覺形成風格反差。',
    role: '視覺設計',
    timeline: '青年聖誕活動',
    team: '獨立完成',
    tools: ['Illustrator', 'Photoshop'],
  },
  {
    id: 'design-ordination',
    title: '按牧感恩禮拜 邀請卡',
    category: 'design',
    tag: '平面設計 · 邀請卡',
    blurb: '按牧典禮的正式邀請卡，以深藍配燙金的紋章與字體，呈現莊重而典雅的儀式感。',
    metric: '正式邀請卡',
    images: ['images/ordination.jpg'],
    summary: '為教會按牧感恩禮拜設計的正式邀請卡，採深藍與燙金的紋章式視覺與襯線字體，正反面一致，傳達莊重、典雅的儀式感。',
    role: '視覺設計',
    timeline: '按牧典禮',
    team: '獨立完成',
    tools: ['Illustrator', 'Photoshop'],
  },
  {
    id: 'design-mama-fun',
    title: '媽媽樂 親子園遊會',
    category: 'design',
    tag: '平面設計 · 活動海報',
    blurb: '母親節親子園遊會海報，用等角遊樂園插畫把闖關、手作與美食變成一座小樂園。',
    metric: '親子活動海報',
    images: ['images/mama.jpg'],
    summary: '為教會母親節「媽媽樂」親子園遊會設計的活動海報，以等角視覺打造「TBC happyland」遊樂園場景，串起親子手作、闖關活動與美食園遊會，活潑又好親近。',
    role: '視覺設計',
    timeline: '母親節活動',
    team: '獨立完成',
    tools: ['Illustrator', 'Photoshop'],
  },
];

window.experience = [
  { period: '2023 - 現在', role: '產品經理', company: 'SaaS 新創 · 內部工具團隊', desc: '負責內部營運工具的 0 到 1，導入 AI 自動化，縮短資料處理流程。' },
  { period: '2021 - 2023', role: '產品設計師', company: '電商平台', desc: '主導結帳與會員流程改版，協作工程與行銷落地，並建立設計系統。' },
  { period: '2019 - 2021', role: '平面設計師', company: '品牌設計工作室', desc: '服務新創與中小企業的品牌識別、主視覺與行銷物料。' },
];
